Bước 5: Chia tập dữ liệu (Dataset Partition)

Xử lý mất cân bằng (Imbalanced Handling) --> Không cần vì đây là bài toán sinh văn bản

Chia tập train/test

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import T5Tokenizer
import torch
from torch.utils.data import Dataset, DataLoader

/home/vophilong/Documents/Deep_learning/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = pd.read_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/final_dataset.csv')
# Xem 5 dòng đầu tiên của dữ liệu
display (data.head())

,Input_Text,Output_Text
0,context: | email: congratulations have a good...,just woke upthnx for your note i believe that ...
1,context: | email: what is the situation with ...,solarc is the system used for ngls etc we do n...
2,context: | email: did you get tg back to yr docs,did not get a commitment just told them i thou...
3,context: | email: what do you think happens i...,or less of the current group we have a market ...
4,context: | email: we are going to have to wor...,i understand if i have too i will dip into my ...

In [3]:
# Chia dữ liệu theo tỷ lệ chuẩn: 80% Train, 10% Validation, 10% Test
train_df, temp_df = train_test_split(data, test_size=0.2, random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

print(f"[1] Phân chia tập dữ liệu thành công:")
print(f"    - Tập Huấn luyện (Train): {len(train_df)} dòng")
print(f"    - Tập Xác thực (Val):   {len(val_df)} dòng")
print(f"    - Tập Kiểm tra (Test):  {len(test_df)} dòng")

# Lưu các tập dữ liệu đã chia ra thành các file CSV riêng biệt
train_df.to_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/dataset_split/train.csv', index=False)
val_df.to_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/dataset_split/val.csv', index=False)
test_df.to_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/dataset_split/test.csv', index=False)

[1] Phân chia tập dữ liệu thành công:
    - Tập Huấn luyện (Train): 5116 dòng
    - Tập Xác thực (Val):   639 dòng
    - Tập Kiểm tra (Test):  640 dòng

In [4]:
# ĐỌc 3 dataset đã chia ra
train_df = pd.read_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/dataset_split/train.csv')
val_df = pd.read_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/dataset_split/val.csv')
test_df = pd.read_csv('/home/vophilong/Documents/Deep_learning/DoAn_Email/dataset/dataset_split/test.csv')
# in 5 dòng đầu tiên của tập train
display(train_df.head())
# in 5 dòng đầu tiên của tập val
display(val_df.head())
# in 5 dòng đầu tiên của tập test
display(test_df.head())

,Input_Text,Output_Text
0,context: | email: yes i am here for the time ...,johnny what do you mean you are there for the ...
1,context: | email: it looks like gaylen is goi...,yes am on thursday will work fine also just tr...
2,context: | email: susan good response be advi...,mike thanks for the inputwe stewed over this f...
3,context: | email: trish i could not access hi...,vince i have left a message wbruce requesting ...
4,context: | email: hey vik do you know how oft...,he publishes it rather sporadically unfortunat...

,Input_Text,Output_Text
0,context: | email: just a reminder to send me ...,i believe it is th ave apt but i am waiting fo...
1,context: | email: thanks anabeth we would lik...,don as promised i talked to someone here who i...
2,context: | email: those two counterparties co...,these are interbook deals and i need to confir...
3,context: | email: i cannot open any of your r...,were you able to open my report this morning i...
4,context: sara attached is salt river projects ...,sara attached is salt river projects isda atta...

,Input_Text,Output_Text
0,context: added comments to gas questions in re...,sections last question yes plant can operate w...
1,context: | email: louise the s c first draft ...,cool and yup to the lawyer probably both of yo...
2,context: | email: gerald i just spoke with ma...,tyrell i have made some revisions to the lates...
3,context: | email: has there been a date set f...,hi thomas scheduled for may th looks like i in...
4,context: | email: hello i hate to bug you wit...,i just talked to bob and i do not know if he i...

In [5]:
from transformers import AutoTokenizer
import torch